INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Jubileu','6455');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Ana','6587');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Lucas','6432');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Ever','6415');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Carla','6466');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Juca Pires','9548');

INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Embraer','EMB195');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Embraer', 'EMB787');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Embraer', 'EMB707');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Boeing', '737');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Boeing', '747');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Boeing', '777');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Airbus', 'A320');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Airbus', 'A330');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Airbus', 'A340');
INSERT INTO MODELO_AERONAVE(FABRICANTE, NOME) VALUES('Airbus', 'A350');

INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBIL', 'Jorge Amado');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBBR', 'Brasilia');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBGR', 'Guarulhos');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBSP', 'São Paulo');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBRJ', 'Rio de Janeiro');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBCG', 'Congonhas');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBVT', 'Vitoria');
INSERT INTO AEROPORTO(ICAO, NOME) VALUES('SBPA', 'Salgado Filho');
