INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Jubileu','6455');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Ana','6587');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Lucas','6432');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Ever','6415');
INSERT INTO PILOTO(NOME, NUM_BREVE) VALUES('Carla','6466');